#include "ft_printf.h"
#include "libft/libft.h"
#include <stdio.h>
#include <string.h>

int	main(void)
{
	//printf("----------original------------\n");
    //printf("original print:  %c\n", '0');
	//ft_printf("my print:        %c\n", '0');
	//printf("original print:  %c \n", '0');
	//ft_printf("my print:        %c \n", '0');
	//printf("original print:  10%c\n", '0');
	//ft_printf("my print:        10%c\n", '0');
	//printf("original print:  %10c\n", '0');
	//ft_printf("my print:        %10c\n", '0');
	//printf("original print:  -10%c\n", '0');
	//ft_printf("my print:        -10%c\n", '0');
	//printf("original print:  %-10c\n", '0');
	//ft_printf("my print:        %-10c\n", '0');
	//printf("original print:  %*c\n", 1, '0');
	//ft_printf("my print:        %*c\n", 1, '0');
	//printf("original print:  %*c\n", 0, '0');
	//ft_printf("my print:        %*c\n", 0, '0');
	//printf("original print:  %*c\n", 2, '0');
	//ft_printf("my print:        %*c\n", 2, '0');
	//printf("original print:  %*c\n", -2, '0');
	//ft_printf("my print:        %*c\n", -2, '0');
	//printf("original print:  %*c\n", 0, '0');
	//ft_printf("my print:        %*c\n", 0, '0');
	//printf("original print:  %*c\n", 10, '0');
	//ft_printf("my print:        %*c\n", 10, '0');
	//printf("original print:  %*c\n", -10, '0');
	//ft_printf("my print:        %*c\n", -10, '0');
	//printf("original print:  %*c%*c\n", -10, '0', 10, '1');
	//ft_printf("my print:        %*c%*c\n", -10, '0', 10, '1');
	//printf("original print:  *%c%*c\n", '0', 10, '1');
	//ft_printf("my print:        *%c%*c\n", '0', 10, '1');
	//printf("original print:  %*c%c*\n", -10, '0', '1');
	//ft_printf("my print:        %*c%c*\n", -10, '0', '1');
	//printf("original print:  %-10c*\n",'0');
	//ft_printf("my print:        %-10c*\n",'0');
	//printf("original print:  %-10c%*c%c*\n",'0', 10, '1', '2');
	//ft_printf("my print:        %-10c%*c%c*\n",'0', 10, '1', '2');
	//printf("original print:  %c%c%c*\n",'0', '1', '2');
	//ft_printf("my print:        %c%c%c*\n",'0', '1', '2');
	//printf("original print:  %-c%-c%c*\n", 1, '0', 0);
	//ft_printf("my print:        %-c%-c%c*\n", 1, '0', 0);
	//printf("original print:  %c\n", '0' - 256);
	//ft_printf("my print:        %c\n", '0' - 256);
	//printf("original print:  %c\n", '0' + 256);
	//ft_printf("my print:        %c\n", '0' + 256);
	//printf("original print:  %c\n", 0);
	//ft_printf("my print:        %c\n", 0);
	//printf("original print:  0%c\n", 0);
	//ft_printf("my print:        0%c\n", 0);
	//printf("original print:  %c\n", -129);
	//ft_printf("my print:        %c\n", -129);
	//printf("original print:  %c\n", 128);
	//ft_printf("my print:        %c\n", 128);
	//printf("original print:  %-*c\n", 10, '1');
	//ft_printf("my print:        %-*c\n", 10, '1');
	//printf("original print:  -%*c* -%-*c* \n", -2, 0, 2, 0);
	//ft_printf("my print:        -%*c* -%-*c* \n", -2, 0, 2, 0);
	//printf("original print:  -%-*c* -%-*c* \n", 2, 0, -2, 0);
	//ft_printf("my print:        -%-*c* -%-*c* \n", 2, 0, -2, 0);
	//printf("original print:  -%*c* -%-*c* \n", -1, 0, 1, 0);
	//ft_printf("my print:        -%*c* -%-*c* \n", -1, 0, 1, 0);
	//printf("original print:  -%-*c* -%-*c* \n", 2, 0, -2, 0);
	//ft_printf("my print:        -%-*c* -%-*c* \n", 2, 0, -2, 0);
	//printf("original print:  -%-2c* -%2c* \n", 0, 0);
	//ft_printf("my print:        -%-2c* -%2c* \n", 0, 0);

	ft_printf("---------return original----------\n");
	printf("\noriginal return: %i\n", printf("%c", '0'));
	printf("\nmy return: %i\n", ft_printf("%c", '0'));
	printf("\noriginal return: %i\n", printf(" %c ", '0'));
	printf("\nmy return: %i\n", ft_printf(" %c ", '0'));
	//printf("\nreturn: %i\n", ft_printf("10%c", '0'));
	//printf("\nreturn: %i\n", ft_printf("%10c", '0'));
	printf("\noriginal return: %i\n", printf("|%*c%*c|", -10, '0', 10, '1'));
	printf("\nmy return: %i\n", ft_printf("|%*c%*c|", -10, '0', 10, '1'));
	//printf("\nreturn: %i\n", ft_printf("%-10c", '0'));
	//printf("\nreturn: %i\n", ft_printf("%*c", 1, '0'));
	//printf("\nreturn: %i\n", ft_printf("%*c", 0, '0'));
	//printf("\nreturn: %i\n", ft_printf("%*c", 2, '0'));
	//printf("\nreturn: %i\n", ft_printf("%*c", -2, '0'));
	//printf("\nreturn: %i\n", ft_printf("%*c", 0, '0'));
	//printf("\nreturn: %i\n", ft_printf("%*c", 10, '0'));
	//printf("\nreturn: %i\n", ft_printf("%*c", -10, '0'));
	//printf("\nreturn: %i\n", ft_printf("%*c%*c", -10, '0', 10, '1'));
	//printf("\nreturn: %i\n", ft_printf("*%c%*c", '0', 10, '1'));
	//printf("\nreturn: %i\n", ft_printf("%*c%c*", -10, '0', '1'));
	//printf("\nreturn: %i\n", ft_printf("%-10c*",'0'));
	//printf("\nreturn: %i\n", ft_printf("%-10c%*c%c*",'0', 10, '1', '2'));
	//printf("\nreturn: %i\n", ft_printf("%c%c%c*",'0', '1', '2'));
	//printf("\nreturn: %i\n", ft_printf("%-c%-c%c*", 1, '0', 0));
	//printf("\nreturn: %i\n", ft_printf("%c", '0' - 256));
	//printf("\nreturn: %i\n", ft_printf("%c", '0' + 256));
	//printf("\nreturn: %i\n", ft_printf("%c", 0));
	//printf("\nreturn: %i\n", ft_printf("0%c", 0));
	//printf("\nreturn: %i\n", ft_printf("%c", -129));
	//printf("\nreturn: %i\n", ft_printf("%c", 128));
	//printf("\nreturn: %i\n", ft_printf("%-*c", 10, '1'));
	//printf("\nreturn: %i\n", ft_printf(" -%*c* -%-*c* ", -2, 0, 2, 0));
	//printf("\nreturn: %i\n", ft_printf(" -%-*c* -%-*c* ", 2, 0, -2, 0));
	//printf("\nreturn: %i\n", ft_printf(" -%*c* -%-*c* ", -1, 0, 1, 0));
	//printf("\nreturn: %i\n", ft_printf(" -%-*c* -%-*c* ", 2, 0, -2, 0));
	//printf("\nreturn: %i\n", ft_printf(" -%-2c* -%2c* ", 0, 0));
}